/** Herminox guides — weighted primary linking (not even). */
export const TOOLS = {
  fba: { id: 'fba', url: '/sellers/fba-calculator/', name: 'FBA Profit Calculator', short: 'Fees, margin & ROI', audience: 'sellers' },
  acos: { id: 'acos', url: '/sellers/acos-breakeven/', name: 'ACoS Breakeven Calculator', short: 'PPC spend ceiling', audience: 'sellers' },
  inv: { id: 'inv', url: '/sellers/inventory-breakeven/', name: 'Inventory Breakeven Calculator', short: 'Units to payback', audience: 'sellers' },
  unit: { id: 'unit', url: '/buyers/unit-price/', name: 'True Unit Price Comparator', short: 'Price per oz / unit', audience: 'buyers' },
  cpu: { id: 'cpu', url: '/buyers/cost-per-use/', name: 'Cost Per Use Calculator', short: 'Lifetime cost', audience: 'buyers' },
  ret: { id: 'ret', url: '/buyers/return-tracker/', name: 'Smart Return & Capital Dashboard', short: 'Deadlines & locked capital', audience: 'buyers' },
};

export function toolById(id) {
  return TOOLS[id];
}

/**
 * Primary weights: FBA×5, ACoS×4, Inv×3, Unit×3, CPU×2, Return×3 = 20
 * Each page: 1 primary CTA + related secondaries + sibling cluster links (added at build).
 */
export const GUIDES = [
  {
    slug: 'amazon-fba-fees-2026',
    primary: 'fba', related: ['inv', 'acos'], audience: 'sellers', readMin: 9,
    query: 'amazon fba fees 2026',
    title: 'Amazon FBA Fees 2026 — Referral, Fulfillment & Fuel',
    description: 'How Amazon FBA fees work in 2026: referral, fulfillment size tiers, and the 3.5% fuel surcharge — with a worked margin example before you buy inventory.',
    h1: 'Amazon FBA fees in <em>2026</em>: the three layers that decide your margin',
    lead: 'Most “bad products” are fee products. Before you place a purchase order, you need referral, fulfillment, and the fuel surcharge in one model — not a vibe-based margin.',
    formula: 'Net profit ≈ Sell price − product cost − referral − FBA fulfillment − (fulfillment × 0.035 if surcharge on)',
    example: { title: 'Worked example', body: 'A $28 standard-size item, $9 landed cost, 15% referral ($4.20), ~$5.40 fulfillment. Fuel at 3.5% adds ~$0.19. Contribution before ads ≈ $28 − $9 − $4.20 − $5.40 − $0.19 = $9.21 (~33% margin). That is pre-PPC — not take-home.' },
    table: {
      headers: ['Fee layer', 'What drives it', '2026 note'],
      rows: [
        ['Referral', 'Category + price bands', 'Often 8–15%; $0.30 minimum on many categories'],
        ['FBA fulfillment', 'Size tier + weight + price band', 'US rate card effective Jan 15, 2026'],
        ['Fuel & logistics', '% of fulfillment fee', '3.5% surcharge widely applied from Apr 17, 2026'],
      ],
    },
    sections: [
      { h2: 'Why “FBA fee” is three numbers, not one', html: '<p>Seller Central payouts feel like a black box because Amazon stacks fees. Referral is a percentage of the selling price (and can include shipping/gift wrap in the base). Fulfillment is a flat-ish per-unit charge from size and weight. The fuel surcharge rides on top of fulfillment — small per unit, loud at 1,000 units.</p><p>If you only model referral, compact heavy items look fine until fulfillment eats the rest. If you ignore fuel, your spreadsheet quietly drifts ~3–4% on fulfillment every month.</p>' },
      { h2: 'What still is not in a simple pre-launch model', html: '<p>Storage, inbound placement, returns processing, and aged inventory surcharges matter at scale. For a go/no-go sourcing decision, referral + fulfillment + fuel usually decide viability. Add storage later when velocity is real — do not skip the first three.</p><ul><li>Confirm final fees in your own Seller Central fee preview.</li><li>Re-run numbers when Amazon publishes a new rate card.</li><li>Treat ad spend as a separate ceiling (ACoS breakeven), not as “misc.”</li></ul>' },
    ],
    checklist: ['Sell price and landed cost entered', 'Correct category (watch tiered categories)', 'Packaged weight and dimensions for size tier', 'Fuel surcharge toggled on if active', 'Margin still healthy after a realistic ACoS'],
    faqs: [
      { q: 'Are 2026 FBA fees the same in every marketplace?', a: 'No. This guide focuses on published US logic. UK/EU/other marketplaces use different schedules — always use the marketplace you sell in.' },
      { q: 'Does free shipping remove the referral fee?', a: 'No. Referral is generally calculated on the total customer payment components Amazon defines for that category — free shipping does not make referral vanish.' },
      { q: 'Should I include PPC in the FBA fee calculator?', a: 'Model fees and product cost first, then set an ad ceiling with breakeven ACoS. Mixing ads into “fees” hides which lever is broken.' },
    ],
  },
  {
    slug: 'amazon-referral-fee-by-category',
    primary: 'fba', related: ['acos'], audience: 'sellers', readMin: 8,
    query: 'amazon referral fee by category',
    title: 'Amazon Referral Fee by Category — Flat vs Tiered',
    description: 'How Amazon referral fees work by category: flat rates, the $0.30 minimum, and why Apparel, Jewelry, and other tiered categories break flat-rate estimates.',
    h1: 'Amazon referral fees by category: <em>flat vs tiered</em>',
    lead: 'A flat “15%” mental model is wrong for whole categories — and expensive when it is wrong on the high side or the low side.',
    formula: 'Referral ≈ max(minimum, category schedule applied to price slices)',
    example: { title: 'Apparel tier sketch', body: 'On a tiered Apparel schedule, a $14.99 shirt may sit mostly in a lower band, while a $22 shirt pays a lower rate on the first slice and a higher rate above it. A flat 17% on $14.99 overstates the fee; a flat 5% on $40 understates it.' },
    table: {
      headers: ['Pattern', 'Examples', 'Modeling tip'],
      rows: [
        ['Flat %', 'Many general merchandise categories', 'One rate × price (then apply minimum)'],
        ['Tiered bands', 'Apparel, Baby, Furniture, Grocery, Jewelry, Shoes, Watches', 'Apply each band to its price slice'],
        ['Minimum', 'Common $0.30 floor', 'Low-price items can pay more than % implies'],
      ],
    },
    sections: [
      { h2: 'Category placement is a margin decision', html: '<p>Two valid browse paths can imply different referral schedules. Before you source, check which category your comparable ASINs actually sit in — and whether that category is flat or tiered. A few points of referral on every unit compounds faster than most packaging tweaks.</p>' },
      { h2: 'Minimum fees punish cheap SKUs', html: '<p>On low sell prices, the minimum referral can dominate. A $3 accessory at a “low %” category can still lose money after minimum referral + fulfillment. Always run dollar fees, not only percentages.</p>' },
    ],
    checklist: ['Identify likely category from live comps', 'Check whether that category is tiered', 'Compute referral in dollars', 'Compare against $0.30 minimum', 'Re-check after any price change'],
    faqs: [
      { q: 'Where do I get official referral rates?', a: 'Amazon publishes selling-fee schedules in Seller Central help documentation. Schedules change — verify the date on the page you use.' },
      { q: 'Can I pick a category just for lower fees?', a: 'Mis-categorization risks suppression and account issues. Model honest placement, not fee shopping.' },
      { q: 'Do referral fees apply to FBM the same way?', a: 'Referral applies to sales regardless of FBA vs FBM; fulfillment differs. Always separate the two in your model.' },
    ],
  },
  {
    slug: 'fba-fuel-surcharge-explained',
    primary: 'fba', related: ['inv'], audience: 'sellers', readMin: 7,
    query: 'amazon fba fuel surcharge',
    title: 'Amazon FBA Fuel Surcharge 2026 — 3.5% Explained',
    description: 'Amazon’s FBA fuel and logistics surcharge: how the 3.5% applies to fulfillment fees, what it costs at volume, and how to model it before you buy inventory.',
    h1: 'The FBA fuel surcharge: <em>3.5%</em> that shows up after you thought fees were done',
    lead: 'Fuel is not a new referral rate. It is a percentage of the fulfillment fee — easy to miss in old spreadsheets built before April 2026.',
    formula: 'Fuel ≈ FBA fulfillment fee × 0.035',
    example: { title: 'Volume math', body: 'At $4.60 fulfillment, fuel ≈ $0.16/unit. On 2,000 units that is ~$320 — often more than a packaging redesign you debated for weeks.' },
    table: {
      headers: ['Fulfillment fee', '3.5% fuel', 'Per 1,000 units'],
      rows: [
        ['$3.22', '$0.11', '$113'],
        ['$5.40', '$0.19', '$189'],
        ['$8.00', '$0.28', '$280'],
      ],
    },
    sections: [
      { h2: 'Where people mis-model it', html: '<p>Do not apply 3.5% to the sell price. Do not apply it to referral. It rides on fulfillment. Turning it “off” in a calculator to make a product look green is how you invent phantom margin.</p>' },
      { h2: 'How it interacts with inventory payback', html: '<p>Fuel raises cost per unit sold, which raises units-to-breakeven on a fixed purchase order. If your payback model ignores fuel, your cash-recovery date is late by design.</p>' },
    ],
    checklist: ['Fulfillment fee estimated from size/weight', 'Fuel toggled on', 'Per-unit and per-PO totals reviewed', 'Margin re-checked after fuel'],
    faqs: [
      { q: 'Is the fuel surcharge permanent?', a: 'Amazon can change surcharges. Treat 3.5% as the active published figure until Amazon updates documentation — then update your model the same week.' },
      { q: 'Does fuel apply to FBM?', a: 'This surcharge is an FBA fulfillment concept. FBM has different shipping cost realities you model yourself.' },
      { q: 'Should I raise price to cover fuel?', a: 'Sometimes. First see whether size-tier optimization or landed-cost negotiation is cheaper than a price hike that hurts conversion.' },
    ],
  },
  {
    slug: 'amazon-fba-profit-margin-benchmarks',
    primary: 'fba', related: ['acos', 'inv'], audience: 'sellers', readMin: 8,
    query: 'good fba profit margin',
    title: 'Good FBA Profit Margin? Benchmarks Before Ads',
    description: 'What counts as a good Amazon FBA profit margin before advertising — practical bands, why sub-15% breaks under PPC, and how to stress-test a SKU.',
    h1: 'What is a <em>good</em> FBA profit margin before ads?',
    lead: 'Margin without an ad ceiling is incomplete. Still, you need a pre-ad floor — or every campaign debate starts from fantasy.',
    formula: 'Pre-ad margin % = (Sell − cost − referral − FBA − fuel) / Sell × 100',
    example: { title: 'Thin margin trap', body: '18% pre-ad margin with a 15% TACoS leaves ~3% — technically positive, operationally fragile after returns and anomalies.' },
    table: {
      headers: ['Pre-ad margin', 'Reading', 'Next step'],
      rows: [
        ['Under 15%', 'Fragile for most PPC-dependent launches', 'Reprice, lighten package, or pass'],
        ['15–30%', 'Workable if ACoS is controlled', 'Set breakeven ACoS; stress-test payback'],
        ['30%+', 'Strong cushion', 'Still model ads and inventory cash'],
      ],
    },
    sections: [
      { h2: 'Benchmarks are not universal laws', html: '<p>Consumables with high repeat and low returns can survive thinner margins than fashion with size returns. Use bands as tripwires, then adjust for category reality — not influencer screenshots.</p>' },
      { h2: 'Always pair margin with cash recovery', html: '<p>A 35% margin SKU that needs 14 months to sell through can still wreck cash flow. Run units-to-breakeven on the real PO size before you celebrate percentage margin.</p>' },
    ],
    checklist: ['Pre-ad margin calculated in dollars and %', 'Breakeven ACoS known', 'Target ACoS set below breakeven', 'PO payback units estimated', 'Return rate sanity check for category'],
    faqs: [
      { q: 'Should margin include my salary?', a: 'For sourcing go/no-go, contribution after Amazon fees and COGS is the first filter. Owner salary belongs in a fuller P&amp;L once the SKU is real.' },
      { q: 'Is ROI better than margin?', a: 'Use both. Margin shows unit health; ROI on inventory shows cash efficiency across the PO.' },
      { q: 'What if my comps sell at a price that kills margin?', a: 'That is your answer: pass, change the offer, or find a structural cost advantage — do not invent a fantasy ASP.' },
    ],
  },
  {
    slug: 'tiered-referral-fees-apparel-jewelry',
    primary: 'fba', related: ['acos'], audience: 'sellers', readMin: 8,
    query: 'amazon tiered referral fees apparel',
    title: 'Tiered Amazon Referral Fees — Apparel, Jewelry & More',
    description: 'How Amazon’s tiered referral fees work for Apparel, Jewelry, Shoes, and related categories — with band math that flat-rate calculators get wrong.',
    h1: 'Tiered referral fees: why Apparel and Jewelry <em>break</em> flat-rate math',
    lead: 'Seven categories do not use a single percentage on the whole price. If your spreadsheet assumes flat rates there, your margin is fiction.',
    formula: 'Fee = Σ (rate_band × dollars_in_band)',
    example: { title: 'Band thinking', body: 'Suppose a schedule charges a lower % on the first $15 and a higher % above. A $14 item and a $30 item are not “the same category rate.” Price changes move you across bands nonlinearly.' },
    table: {
      headers: ['Category family', 'Why it matters', 'Operator habit'],
      rows: [
        ['Apparel / Shoes', 'Fashion pricing sits near band edges', 'Recompute fee on every price test'],
        ['Jewelry', 'High rates + price sensitivity', 'Model dollar fee before bidding on ads'],
        ['Grocery / Baby / Furniture / Watches', 'Tier rules differ by schedule', 'Never copy another category’s bands'],
      ],
    },
    sections: [
      { h2: 'Price tests change fee % in tiered categories', html: '<p>In a flat category, a $1 price cut changes referral roughly linearly. In a tiered category, a $1 cut can also change which band dollars sit in — so contribution can jump more than you expect. Always re-run fee math when you A/B price.</p>' },
      { h2: 'PPC ceilings depend on correct referral', html: '<p>Breakeven ACoS is margin-based. If referral is wrong by 3–5 points, your entire PPC “safe zone” shifts. Fix fee truth before you scale Sponsored Products.</p>' },
    ],
    checklist: ['Confirm category is tiered', 'Use band math, not a single %', 'Recompute after price changes', 'Feed correct referral into ACoS breakeven'],
    faqs: [
      { q: 'Which categories are tiered?', a: 'Commonly cited tiered groups include Apparel, Baby, Furniture, Grocery &amp; Gourmet, Jewelry, Shoes, and Watches — verify against Amazon’s current US fee schedule.' },
      { q: 'Can I approximate with an average %?', a: 'For rough brainstorming only. For POs and ads, use band math or a calculator that implements bands.' },
      { q: 'Does tiering affect FBA fulfillment?', a: 'Tiered referral is separate from fulfillment size tiers. Model both; do not conflate them.' },
    ],
  },
  {
    slug: 'amazon-acos-breakeven-formula',
    primary: 'acos', related: ['fba'], audience: 'sellers', readMin: 8,
    query: 'acos breakeven formula',
    title: 'ACoS Breakeven Formula — Max Ad Spend Before You Lose',
    description: 'The Amazon ACoS breakeven formula in plain English: how to turn pre-ad margin into a hard PPC ceiling, with a numeric example.',
    h1: 'Breakeven ACoS: the formula that stops <em>hope-based</em> PPC',
    lead: 'If you do not know the ACoS where ad sales stop being profitable, you are not “testing” — you are donating margin.',
    formula: 'Breakeven ACoS % ≈ Pre-ad profit per unit / Sell price × 100',
    example: { title: 'Numbers', body: 'Sell $30, pre-ad profit $9 → breakeven ACoS = 30%. A 35% ACoS on ad-attributed sales loses money on those sales even if total store revenue looks fine.' },
    table: {
      headers: ['Pre-ad profit', 'Sell price', 'Breakeven ACoS'],
      rows: [
        ['$6', '$24', '25%'],
        ['$9', '$30', '30%'],
        ['$12', '$40', '30%'],
      ],
    },
    sections: [
      { h2: 'Breakeven is a ceiling, not a target', html: '<p>Operators usually aim for 50–75% of breakeven ACoS so returns, fee drift, and bad weeks do not erase contribution. Launch periods can temporarily run hotter — with a budget cap and an end date.</p>' },
      { h2: 'Garbage in: fees wrong → ACoS wrong', html: '<p>Compute pre-ad profit with real referral and FBA (including fuel). Then compute breakeven ACoS. Skipping the fee step produces a confident, incorrect bid strategy.</p>' },
    ],
    checklist: ['Pre-ad profit known in dollars', 'Breakeven ACoS computed', 'Target ACoS set below breakeven', 'Campaign budgets capped'],
    faqs: [
      { q: 'Is breakeven ACoS the same as TACoS?', a: 'No. ACoS uses ad-attributed sales; TACoS uses total sales. Both matter; they answer different questions.' },
      { q: 'Does breakeven include organic sales?', a: 'Classic breakeven ACoS is about ad-driven sales profitability. Organic mix shows up when you interpret TACoS.' },
      { q: 'What if my ACoS is above breakeven but rank is rising?', a: 'That can be a deliberate launch investment. Treat it as capped CAC, not as “good ACoS.”' },
    ],
  },
  {
    slug: 'acos-vs-tacos-explained',
    primary: 'acos', related: ['fba'], audience: 'sellers', readMin: 8,
    query: 'acos vs tacos amazon',
    title: 'ACoS vs TACoS Explained — Which Metric to Trust',
    description: 'ACoS vs TACoS on Amazon: what each measures, why TACoS falls as organic share rises, and how to use both without lying to yourself.',
    h1: 'ACoS vs TACoS: stop using <em>one</em> metric for two jobs',
    lead: 'ACoS tells you about ad efficiency. TACoS tells you about ad burden on the whole business. Confusing them creates false confidence.',
    formula: 'TACoS ≈ ACoS × (1 − organic share)',
    example: { title: 'Organic flywheel', body: 'ACoS 30% with 10% organic → TACoS ~27%. Same ACoS with 60% organic → TACoS ~12%. The ad engine did not magically improve — the denominator did.' },
    table: {
      headers: ['Metric', 'Denominator', 'Use it to'],
      rows: [
        ['ACoS', 'Ad-attributed sales', 'Judge campaign/keyword efficiency'],
        ['TACoS', 'Total sales', 'Judge ad load on the SKU/account'],
        ['Breakeven ACoS', 'Margin-based ceiling', 'Set maximum affordable ACoS'],
      ],
    },
    sections: [
      { h2: 'Healthy pattern as listings mature', html: '<p>Early: higher ACoS, higher TACoS, low organic. Mature: ACoS may stay moderate while TACoS falls if organic share grows. If both stay high for months, you are renting sales, not building an asset.</p>' },
      { h2: 'Reporting tip', html: '<p>Review ACoS weekly for optimization. Review TACoS weekly for strategy. Never celebrate a TACoS drop that came only from pausing ads and watching sales collapse.</p>' },
    ],
    checklist: ['Track ACoS and TACoS on the same dashboard', 'Estimate organic share monthly', 'Compare ACoS to breakeven, not to internet averages', 'Separate launch budgets from evergreen budgets'],
    faqs: [
      { q: 'What is a good TACoS?', a: 'It depends on margin and growth stage. Use breakeven ACoS and contribution after ads — not a universal TACoS myth number.' },
      { q: 'Can TACoS be higher than ACoS?', a: 'No — if definitions are standard, TACoS ≤ ACoS because total sales ≥ ad sales.' },
      { q: 'Should beginners ignore TACoS?', a: 'No. Beginners over-focus on ACoS while burning cash. TACoS keeps the whole P&amp;L in view.' },
    ],
  },
  {
    slug: 'amazon-max-cpc-from-margin',
    primary: 'acos', related: ['fba'], audience: 'sellers', readMin: 7,
    query: 'amazon max cpc calculator',
    title: 'Amazon Max CPC from Margin — Bid Ceiling Math',
    description: 'How to calculate maximum CPC on Amazon from breakeven ACoS and conversion rate — so bids stay inside a profitable ceiling.',
    h1: 'Max CPC: turn margin into a <em>bid ceiling</em>',
    lead: 'Bids without a max CPC are vibes. Conversion rate and breakeven ACoS give you a number you can defend.',
    formula: 'Max CPC ≈ Price × (Breakeven ACoS / 100) × (CVR / 100)',
    example: { title: 'Worked bid', body: '$30 price, 40% breakeven ACoS, 10% CVR → max CPC = 30 × 0.40 × 0.10 = $1.20. Many operators bid 50–80% of max CPC for cushion.' },
    table: {
      headers: ['CVR', 'Breakeven ACoS', 'Price $30 → max CPC'],
      rows: [
        ['8%', '35%', '$0.84'],
        ['10%', '35%', '$1.05'],
        ['12%', '40%', '$1.44'],
      ],
    },
    sections: [
      { h2: 'CVR is the hidden lever', html: '<p>Improving the listing (images, title, reviews velocity quality) raises CVR and raises affordable CPC without raising ACoS targets. Fixing conversion often beats blindly raising bids.</p>' },
      { h2: 'Placement modifiers need the same ceiling logic', html: '<p>Top-of-search multipliers can push effective CPC above your max. Recalculate after modifiers — not only on base bid.</p>' },
    ],
    checklist: ['Breakeven ACoS from real fees', 'CVR from recent Sponsored Products data', 'Max CPC computed', 'Bid set below max', 'Modifiers checked'],
    faqs: [
      { q: 'Which CVR should I use?', a: 'Prefer ad CVR for the campaign type you are bidding on. Blended store CVR can mislead on cold keywords.' },
      { q: 'What if max CPC is below $0.40?', a: 'That SKU may not support paid traffic at current margin/CVR. Improve offer economics before buying clicks.' },
      { q: 'Does this work for Sponsored Brands?', a: 'Same economics apply, but attribution and CVR differ — recompute with SB-specific conversion assumptions.' },
    ],
  },
  {
    slug: 'launch-vs-profit-acos-strategy',
    primary: 'acos', related: ['fba', 'inv'], audience: 'sellers', readMin: 8,
    query: 'launch acos vs target acos',
    title: 'Launch ACoS vs Profit ACoS — Two Modes, One Ceiling',
    description: 'How to run Amazon launch ACoS versus profit ACoS: temporary investment rules, budget caps, and when to switch back to contribution mode.',
    h1: 'Launch ACoS vs profit ACoS: <em>two modes</em>, one honest ledger',
    lead: 'Launch mode is allowed. Infinite launch mode is how brands rent page-one forever and call it growth.',
    formula: 'Launch spend must be capped: Budget ≤ planned CAC × expected launch units',
    example: { title: 'Switch rule', body: 'If after 4–6 weeks organic share is flat and TACoS is not improving, you are not investing — you are stuck. Cut to profit ACoS or fix the offer.' },
    table: {
      headers: ['Mode', 'ACoS posture', 'Exit condition'],
      rows: [
        ['Launch', 'Near or above breakeven, time-boxed', 'Organic share ↑ or date hit'],
        ['Profit', '50–75% of breakeven', 'Contribution positive after ads'],
        ['Rescue', 'Cuts + listing fixes', 'Stop funding a broken offer'],
      ],
    },
    sections: [
      { h2: 'Write the launch hypothesis down', html: '<p>Example: “Spend up to $X over 30 days to reach Y units/day and Z% organic.” If you cannot write it, you cannot audit it. Pair with inventory so you do not stockout mid-push or overbuy into a failed test.</p>' },
      { h2: 'Inventory coupling', html: '<p>Aggressive launch ACoS on a thin inbound PO creates stockouts that erase rank gains. Aggressive inventory without an ad plan creates aged stock. Launch is a cash + ads + inbound triangle.</p>' },
    ],
    checklist: ['Breakeven ACoS known', 'Launch budget and end date set', 'Inventory covers the test', 'Weekly TACoS/organic review', 'Switch criteria defined'],
    faqs: [
      { q: 'How long should launch mode last?', a: 'Often weeks, not quarters. Category competition changes the calendar — the point is a pre-committed end, not a feeling.' },
      { q: 'Can launch ACoS exceed breakeven?', a: 'Yes, as capped CAC. Never as an unlabeled default.' },
      { q: 'What metric proves launch worked?', a: 'Improving organic share and falling TACoS at stable or rising sales — not ACoS alone.' },
    ],
  },
  {
    slug: 'inventory-breakeven-units-amazon',
    primary: 'inv', related: ['fba'], audience: 'sellers', readMin: 8,
    query: 'inventory breakeven units amazon',
    title: 'Inventory Breakeven Units — How Many Sales Recover a PO',
    description: 'Calculate how many Amazon units you must sell to recover a purchase order — capital tied up, contribution per unit, and why margin % alone is not enough.',
    h1: 'Inventory breakeven units: when does this PO <em>pay you back</em>?',
    lead: 'Percentage margin can look great while cash stays trapped. Units-to-recover is the question factories understand.',
    formula: 'Units to recover ≈ PO cash outlay / Contribution per unit after fees',
    example: { title: 'PO sketch', body: 'PO cash $8,000. Contribution after Amazon fees $4/unit. You need ~2,000 units sold to recover cash — before counting profit beyond breakeven.' },
    table: {
      headers: ['Contribution / unit', 'PO cash', 'Units to recover'],
      rows: [
        ['$3', '$6,000', '2,000'],
        ['$5', '$6,000', '1,200'],
        ['$8', '$10,000', '1,250'],
      ],
    },
    sections: [
      { h2: 'Define “cash outlay” honestly', html: '<p>Include product, inbound freight, prep, and other cash that leaves before sell-through. Excluding inbound is a classic way to fake a fast payback.</p>' },
      { h2: 'Fee truth required', html: '<p>Contribution per unit must use real referral + FBA + fuel. Inflated contribution understates units-to-recover and overstates how safe the PO is.</p>' },
    ],
    checklist: ['Full PO cash listed', 'Contribution/unit after fees', 'Units-to-recover computed', 'Sell-through timeline estimated', 'Storage risk considered for slow SKUs'],
    faqs: [
      { q: 'Is breakeven units the same as MOQ?', a: 'No. MOQ is what the supplier forces; breakeven units is what economics require. Sometimes MOQ &gt; sane breakeven — that is a pass signal.' },
      { q: 'Do returns change the number?', a: 'Yes. Effective contribution falls when return rates rise. Haircut contribution for high-return categories.' },
      { q: 'Should I include ad spend in contribution?', a: 'For cash recovery of inventory, start with fee-adjusted product contribution, then layer ads as a separate cash drain with its own budget.' },
    ],
  },
  {
    slug: 'amazon-inventory-payback-period',
    primary: 'inv', related: ['fba', 'acos'], audience: 'sellers', readMin: 8,
    query: 'amazon inventory payback period',
    title: 'Amazon Inventory Payback Period — Time to Recover Cash',
    description: 'Estimate Amazon inventory payback period from sell-through rate and units-to-breakeven — so you see months of cash lock before you reorder.',
    h1: 'Inventory payback period: translate units into <em>months</em>',
    lead: 'Units-to-recover without velocity is incomplete. Payback period tells you how long your cash is hostage.',
    formula: 'Payback months ≈ Units to recover / Monthly sell-through units',
    example: { title: 'Velocity matter', body: '2,400 units to recover at 400 units/month ≈ 6 months. Same PO at 200 units/month ≈ 12 months — a different business risk.' },
    table: {
      headers: ['Monthly units', 'Units to recover', 'Payback'],
      rows: [
        ['300', '1,200', '4 months'],
        ['300', '2,400', '8 months'],
        ['150', '2,400', '16 months'],
      ],
    },
    sections: [
      { h2: 'Seasonality lies to annual averages', html: '<p>A Q4 spike can hide a dead Q2. Model payback on conservative velocity, not peak week screenshots from Keepa.</p>' },
      { h2: 'Ads can pull payback forward — or destroy contribution', html: '<p>Paid velocity shortens payback only if contribution after ads stays sensible. Fast sell-through at negative contribution is just a quicker way to lose the PO.</p>' },
    ],
    checklist: ['Units-to-recover known', 'Conservative monthly velocity set', 'Payback months computed', 'Compared to storage/aging risk', 'Reorder timing planned after payback'],
    faqs: [
      { q: 'What payback is “good”?', a: 'Depends on capital cost and category. Many operators dislike double-digit months on unproven SKUs — treat long payback as higher risk, not automatically “patient investing.”' },
      { q: 'How do stockouts affect payback?', a: 'Stockouts pause recovery and can erase rank. Payback math assumes you can actually sell; inbound planning is part of the model.' },
      { q: 'Is sell-through the same as sessions?', a: 'No. Sell-through is units sold against inventory. Sessions without conversion do not recover cash.' },
    ],
  },
  {
    slug: 'fba-capital-tied-up-explained',
    primary: 'inv', related: ['fba'], audience: 'sellers', readMin: 7,
    query: 'fba capital tied up inventory',
    title: 'FBA Capital Tied Up — See Cash Stuck in Stock',
    description: 'What “capital tied up” means for Amazon FBA inventory: how to estimate trapped cash, why oversizing POs hurts, and how to review it before reorder.',
    h1: 'Capital tied up: the FBA number that <em>margin %</em> hides',
    lead: 'You can be “profitable on paper” and still unable to fund the next PO because cash is sitting in plastic in a warehouse.',
    formula: 'Capital tied up ≈ Remaining units × landed cash cost per unit',
    example: { title: 'Reorder discipline', body: 'If $12,000 is still tied in slow colorways, a new “winning” SKU PO may need outside cash. That is an inventory portfolio problem, not a motivation problem.' },
    table: {
      headers: ['Signal', 'Healthy', 'Warning'],
      rows: [
        ['Age of stock', 'Turns on plan', 'Aging toward surcharges'],
        ['Tied capital', 'Declining as planned', 'Flat/up while ads spend rises'],
        ['SKU count', 'Focused', 'Many dead variants'],
      ],
    },
    sections: [
      { h2: 'Variants multiply trapped cash', html: '<p>Size/color expansion feels like merchandising and behaves like mini-POs. Track tied capital by variant, not only by parent ASIN averages.</p>' },
      { h2: 'Tie capital reviews to fee models', html: '<p>When contribution/unit shrinks (fee hikes, price war), the same unit count represents worse capital efficiency. Re-run FBA economics when the catalog gets heavy.</p>' },
    ],
    checklist: ['Landed cost per unit known', 'Units on hand by SKU', 'Tied capital summed', 'Dead stock flagged', 'Next PO sized against free cash'],
    faqs: [
      { q: 'Is tied capital the same as COGS on the P&amp;L?', a: 'Related but not identical. Tied capital is a cash/balance-sheet view of unsold inventory; P&amp;L recognizes COGS when sold.' },
      { q: 'Should I liquidate to free capital?', a: 'Sometimes yes — paying to exit can beat months of storage and opportunity cost. Run numbers; do not emotional-hoard.' },
      { q: 'How often should I review tied capital?', a: 'Weekly for paid launches; at least monthly for the full catalog.' },
    ],
  },
  {
    slug: 'amazon-unit-price-comparison-guide',
    primary: 'unit', related: ['cpu'], audience: 'buyers', readMin: 7,
    query: 'amazon unit price comparison',
    title: 'Amazon Unit Price Comparison — Per Oz, Count & Liter',
    description: 'How to compare Amazon unit prices fairly across pack sizes: normalize ounces, counts, and volumes so multipacks stop winning on packaging theater.',
    h1: 'Unit price comparison: make Amazon pack sizes <em>comparable</em>',
    lead: 'Listings sell packages. You buy units. Until you normalize, the “best deal” badge is just layout.',
    formula: 'Unit price = Pack price / Quantity in a common unit',
    example: { title: 'Oz trap', body: 'A $12 / 10 oz jar is $1.20/oz. A $18 / 16 oz jar is $1.125/oz. The larger jar wins on unit price even when the headline price is higher.' },
    table: {
      headers: ['Family', 'Normalize to', 'Watch-out'],
      rows: [
        ['Weight', 'oz or lb', 'Net weight vs shipping weight'],
        ['Volume', 'fl oz or mL', 'Concentrates vs ready-to-use'],
        ['Count', 'per piece', '“Up to” sheet counts'],
      ],
    },
    sections: [
      { h2: 'Mixed units need a family first', html: '<p>Convert lb→oz or L→mL inside one family. Do not compare oz to count. Good comparators refuse illegal mixes instead of inventing fake math.</p>' },
      { h2: 'When unit price is not enough', html: '<p>Durables need cost-per-use. Unit price wins for consumables; lifetime cost wins for shoes, tools, and appliances.</p>' },
    ],
    checklist: ['Same product family compared', 'Quantities converted to one unit', 'Unit prices ranked', 'Quality/return risk considered', 'Subscribe &amp; Save math checked separately'],
    faqs: [
      { q: 'Why doesn’t Amazon always show unit price?', a: 'Display rules vary by category and seller data quality. Assume you may need to compute it yourself.' },
      { q: 'Do coupons change the method?', a: 'Use the price you actually pay after coupon, then divide by quantity.' },
      { q: 'What about shipping?', a: 'If one option adds shipping, include it in pack price before dividing — otherwise “free” shipping offers distort the winner.' },
    ],
  },
  {
    slug: 'shrinkflation-unit-price-math',
    primary: 'unit', related: ['cpu'], audience: 'buyers', readMin: 7,
    query: 'shrinkflation unit price',
    title: 'Shrinkflation Math — Same Price, Less Product',
    description: 'Detect shrinkflation with unit price math: same shelf price, less net quantity — and how to compare old vs new packs on Amazon.',
    h1: 'Shrinkflation: catch a silent price hike with <em>unit math</em>',
    lead: 'When the bag looks familiar but net weight fell 8%, you got a price increase without a red clearance tag.',
    formula: 'Effective price change % ≈ New unit price / Old unit price − 1',
    example: { title: 'Sheets example', body: 'Old: $20 / 200 count = $0.10 each. New: $20 / 180 count = $0.111. That is an ~11% unit-price hike at the same sticker.' },
    table: {
      headers: ['Sticker', 'Qty old → new', 'Unit price story'],
      rows: [
        ['Same', 'Down', 'Hidden increase'],
        ['Up slightly', 'Down', 'Compound increase'],
        ['Down', 'Down more', 'Still may be worse per unit'],
      ],
    },
    sections: [
      { h2: 'How to audit a “same” product', html: '<p>Save net quantity from the previous order email or label photo. Compare to today’s detail page. Marketing copy will not announce shrinkflation; the nutrition/net-content line will.</p>' },
      { h2: 'Multipacks can hide it twice', html: '<p>Fewer units per inner pack × fewer inners per case is a double shrink. Always expand to total count/weight before dividing.</p>' },
    ],
    checklist: ['Old net qty recorded', 'New net qty recorded', 'Unit prices compared', 'Decide switch brand / size / skip'],
    faqs: [
      { q: 'Is shrinkflation illegal?', a: 'Generally it is a legal packaging/pricing practice when net contents are disclosed. Your defense is measurement, not outrage alone.' },
      { q: 'Does Subscribe &amp; Save protect me?', a: 'No. Discounts apply to the current pack. If quantity shrank, unit price can still worsen.' },
      { q: 'What if quantity is missing on the page?', a: 'Open images/label text or ask the seller. Without quantity, refuse the comparison — do not guess.' },
    ],
  },
  {
    slug: 'multipack-vs-single-unit-price',
    primary: 'unit', related: ['cpu'], audience: 'buyers', readMin: 7,
    query: 'multipack vs single unit price amazon',
    title: 'Multipack vs Single on Amazon — When “Value” Loses',
    description: 'Multipack vs single-item unit price on Amazon: when bulk is cheaper, when it is a trap, and how to compare without falling for “value pack” labels.',
    h1: 'Multipack vs single: when the value pack is <em>not</em> the value',
    lead: 'Bulk is a financing decision plus a unit-price decision. Winning on neither is how closets fill with “deals.”',
    formula: 'Compare: price_multi / total_units  vs  price_single / units_single',
    example: { title: 'Common outcome', body: 'Single: $9 for 2 = $4.50/unit. Twin multipack: $20 for 4 = $5.00/unit. The multipack costs more per unit and ties more cash.' },
    table: {
      headers: ['Situation', 'Likely winner', 'Why'],
      rows: [
        ['Multipack lower unit price + you will use it', 'Multipack', 'True savings'],
        ['Multipack higher unit price', 'Single', 'Label lied'],
        ['Lower unit price but expires', 'Single / smaller', 'Waste destroys savings'],
      ],
    },
    sections: [
      { h2: 'Cash and storage are part of the deal', html: '<p>Even a true unit-price win can be a bad buy if money is tight or the product expires. Unit price is necessary, not sufficient.</p>' },
      { h2: 'Return windows and bulk', html: '<p>Bulk mistakes are harder to unwind. If you are unsure, prefer a single first order — then multipack after you confirm fit/quality.</p>' },
    ],
    checklist: ['Total units computed', 'Unit prices compared', 'Expiry/usage rate considered', 'Storage space considered', 'Return risk considered'],
    faqs: [
      { q: 'Are warehouse club packs always cheaper on Amazon?', a: 'No. Amazon multipacks are often just bundled singles at a premium. Math beats branding.' },
      { q: 'Should I include tax?', a: 'If tax differs by seller/state in your checkout, include the landed price you pay.' },
      { q: 'What about “amazon’s choice” badges?', a: 'Ignore badges for unit economics. They optimize for conversion, not your per-unit cost.' },
    ],
  },
  {
    slug: 'cost-per-use-vs-sticker-price',
    primary: 'cpu', related: ['unit'], audience: 'buyers', readMin: 8,
    query: 'cost per use vs price',
    title: 'Cost Per Use vs Sticker Price — Lifetime Value Math',
    description: 'Cost per use vs sticker price: how to compare products by lifetime cost so cheap items that die early stop winning your cart.',
    h1: 'Cost per use vs sticker price: buy the <em>wear</em>, not the tag',
    lead: 'Sticker price answers “what do I pay today?” Cost per use answers “what do I pay for each time this thing does its job?”',
    formula: 'Cost per use = (Price + lifetime upkeep) / Expected uses',
    example: { title: 'Boots sketch', body: '$60 boots × 40 wears = $1.50/wear. $220 boots × 200 wears = $1.10/wear — cheaper per use if the durability assumption is real.' },
    table: {
      headers: ['Item type', 'Prefer', 'Why'],
      rows: [
        ['Consumables', 'Unit price', 'Quantity is the product'],
        ['Durables', 'Cost per use', 'Lifespan dominates'],
        ['Hybrid (refills)', 'Both', 'Device + consumable system'],
      ],
    },
    sections: [
      { h2: 'Upkeep belongs in the numerator', html: '<p>Filters, sharpening, batteries, resoling — if you will pay it, include it. Excluding upkeep is how “cheap” printers become expensive.</p>' },
      { h2: 'Be honest about expected uses', html: '<p>Inflating lifespan to justify a splurge is the buyer version of fake seller margins. Use conservative wears based on your actual habits.</p>' },
    ],
    checklist: ['Price entered', 'Upkeep estimated', 'Uses estimated conservatively', 'Cost/use compared across options', 'Return window noted if unsure'],
    faqs: [
      { q: 'Is cost per use the same as cost per day?', a: 'Related. Cost per day = total ownership cost / days kept. Use the denominator that matches how you consume the product.' },
      { q: 'What if I might not use it much?', a: 'Then expected uses fall and expensive durables look worse — correctly. Do not buy capacity you will not use.' },
      { q: 'Can unit price and cost per use disagree?', a: 'Yes. A cheaper-per-oz soap in a dispenser system might lose on cost-per-handwash after wasted product — rare, but possible. Pick the metric that matches the job.' },
    ],
  },
  {
    slug: 'when-expensive-beats-cheap',
    primary: 'cpu', related: ['unit', 'ret'], audience: 'buyers', readMin: 8,
    query: 'when is expensive product cheaper',
    title: 'When Expensive Beats Cheap — Durability Math',
    description: 'When an expensive product is actually cheaper: durability math, replacement cycles, and when to walk away from premium pricing theater.',
    h1: 'When expensive beats cheap — and when it is just <em>marketing</em>',
    lead: 'Premium is not automatically smarter. Run replacement cycles. Sometimes the $40 item winning three times still beats the $180 icon.',
    formula: 'Years to parity ≈ (Price_expensive − Price_cheap) / (annual cost gap from replacements)',
    example: { title: 'Replacement cycle', body: 'Cheap tool $35 lasts 1 year. Better tool $120 lasts 5 years. Five-year spend: cheap $175 vs better $120 — premium wins if lifespan is real.' },
    table: {
      headers: ['Claim', 'Test', 'Fail mode'],
      rows: [
        ['“Lasts forever”', 'Conservative lifespan', 'Fashion/obsolescence'],
        ['“Pro quality”', 'Your use case match', 'Overbuying features'],
        ['“Save money long run”', 'Cost/use math', 'You rarely use it'],
      ],
    },
    sections: [
      { h2: 'Premium theater checklist', html: '<p>If the seller cannot state materials, warranty, or serviceability, you are buying vibe. Cost-per-use needs boring specifics.</p>' },
      { h2: 'Use the return window as a test period', html: '<p>For borderline durables, track the return deadline the day you buy. A short test at home beats a five-year fantasy lifespan assumption.</p>' },
    ],
    checklist: ['Both options’ prices listed', 'Lifespan assumptions written down', 'Cost/use computed', 'Warranty compared', 'Return deadline logged if unsure'],
    faqs: [
      { q: 'What if reviews conflict on durability?', a: 'Weight verified purchase reviews that mention months/years of use. Ignore day-one hype either way.' },
      { q: 'Does financing change the math?', a: 'Interest increases effective price. Add it to the expensive option’s numerator if you carry a balance.' },
      { q: 'Should I always buy mid-range?', a: 'No. Mid-range is a stereotype. Compute; sometimes cheap disposable is correct for rare tasks.' },
    ],
  },
  {
    slug: 'amazon-holiday-return-deadline',
    primary: 'ret', related: ['unit'], audience: 'buyers', readMin: 8,
    query: 'amazon holiday return deadline january 31',
    title: 'Amazon Holiday Return Deadline — January 31 Rule',
    description: 'Amazon holiday return window explained: how November–December purchases often extend to January 31, and how to track deadlines so you do not miss refunds.',
    h1: 'Amazon holiday returns: why <em>January 31</em> matters',
    lead: 'Holiday purchase windows are extended for a reason — and missed by people who assume “30 days from delivery” on a December 20 order.',
    formula: 'Track: purchase date → policy window (standard vs holiday extension) → reminder dates',
    example: { title: 'Classic miss', body: 'Bought Dec 18, assumed 30 days → mid-January panic. Holiday extension to Jan 31 would have covered a calmer return — if tracked.' },
    table: {
      headers: ['Purchase timing', 'Typical pattern', 'Action'],
      rows: [
        ['Nov 1–Dec 31 (eligible items)', 'Often extended to Jan 31', 'Log deadline explicitly'],
        ['Outside holiday window', 'Standard category window', 'Use standard policy'],
        ['Excluded categories', 'Shorter / special rules', 'Check item eligibility'],
      ],
    },
    sections: [
      { h2: 'Policies change — verify for your order', html: '<p>Retailers adjust holiday language yearly. Treat Jan 31 as a common Amazon/Walmart-style pattern to model, then confirm on your order’s return page. Tools help you remember; the order page is source of truth.</p>' },
      { h2: 'Two reminders beat one', html: '<p>A 7-day and 2-day reminder prevents “I’ll do it this weekend” failures. Calendar exports exist for a reason — use them on high-ticket items.</p>' },
    ],
    checklist: ['Order date recorded', 'Holiday vs standard window checked', 'Deadline date saved', 'Reminders set', 'Item condition requirements read'],
    faqs: [
      { q: 'Does every Amazon item get the holiday extension?', a: 'No. Some categories and sellers differ. Always check the return eligibility panel for that order line.' },
      { q: 'Is January 31 based on delivery or order date?', a: 'Follow the policy text on your order. Do not assume — the detail page for returns states which date logic applies.' },
      { q: 'What about third-party sellers?', a: 'Marketplace seller returns can differ from Amazon-fulfilled items. Read that seller’s return terms.' },
    ],
  },
  {
    slug: 'locked-capital-in-unreturned-items',
    primary: 'ret', related: ['cpu'], audience: 'buyers', readMin: 7,
    query: 'locked capital returns amazon',
    title: 'Locked Capital in Returns — Money Sitting in Maybe-Keep Items',
    description: 'Locked capital in unreturned purchases: how “might keep” items trap cash past return windows, and how a simple scoreboard prevents expensive indecision.',
    h1: 'Locked capital: the quiet cost of <em>maybe I’ll keep it</em>',
    lead: 'Every undecided purchase is a mini inventory problem. When the window closes, the decision was made for you — usually badly.',
    formula: 'Locked capital ≈ Σ price of items still inside return window and undecided',
    example: { title: 'Cart of maybes', body: 'Three items at $80, $120, $200 undecided = $400 locked. Missing one deadline on the $200 item costs more than hours of comparison shopping saved.' },
    table: {
      headers: ['Behavior', 'Capital effect', 'Fix'],
      rows: [
        ['Buy now, decide later', 'High lock', 'Deadline scoreboard'],
        ['Decide at purchase', 'Low lock', 'Stricter cart'],
        ['Miss window', 'Capital becomes cost', 'Reminders + fewer impulse SKUs'],
      ],
    },
    sections: [
      { h2: 'Indecision is an interest-free loan to the retailer', html: '<p>Your card is charged; the product sits; the window shrinks. Tracking locked capital makes the cost of delay visible — which is usually enough to decide.</p>' },
      { h2: 'Pair with cost-per-use for durables', html: '<p>If you are delaying because you cannot tell whether premium was worth it, run cost-per-use with conservative wears. Then keep or return before the deadline.</p>' },
    ],
    checklist: ['List undecided items', 'Sum locked capital', 'Sort by deadline', 'Decide or schedule decision', 'Return labels started early for heavy items'],
    faqs: [
      { q: 'Is locked capital a real accounting term?', a: 'Here it is a practical cash concept: money spent on items you might still reverse. Useful for households and operators alike.' },
      { q: 'Should I return everything by default?', a: 'No. Return what fails the decision criteria. The point is a decision, not maximal returns.' },
      { q: 'What about restocking fees?', a: 'Include them in the keep-vs-return math when applicable — they reduce the value of returning late or opened items.' },
    ],
  },
  {
    slug: 'amazon-return-window-mistakes',
    primary: 'ret', related: ['unit'], audience: 'buyers', readMin: 8,
    query: 'amazon return window mistakes',
    title: 'Amazon Return Window Mistakes That Cost Real Money',
    description: 'Common Amazon return-window mistakes: wrong start dates, category exceptions, waiting to “decide later,” and how to build a no-drama return habit.',
    h1: 'Return-window mistakes that turn deals into <em>donations</em>',
    lead: 'Most lost refunds are process failures, not policy mysteries. Fix the habit loop and the math starts working again.',
    formula: 'Habit: purchase → log deadline → mid-window check → keep/return',
    example: { title: 'Day-28 problem', body: 'Doubt often arrives near the end of a 30-day window. Tracking on day 0 gives you the full window to test — not a panic ship on day 29.' },
    table: {
      headers: ['Mistake', 'Result', 'Prevention'],
      rows: [
        ['Assume 30 days always', 'Miss shorter windows', 'Read line-item policy'],
        ['Track in your head', 'Forget', 'Dashboard + calendar'],
        ['Open everything late', 'Fail condition checks', 'Inspect early'],
        ['Ignore seller differences', 'Unexpected denial', 'Note FBA vs seller'],
      ],
    },
    sections: [
      { h2: 'Start tracking at purchase, not at regret', html: '<p>The Return Dashboard pattern is simple: capture the item when the order email arrives. Waiting until you “might return it” is how day-28 shows up.</p>' },
      { h2: 'Unit-price winners still need windows', html: '<p>A great per-oz buy that arrives damaged is only a win if you still have time to reverse it. Deal hunting without deadline hygiene is incomplete.</p>' },
    ],
    checklist: ['Policy read per line item', 'Deadline logged same day', 'Inspection within 48 hours', 'Reminder set', 'Keep box if return-likely'],
    faqs: [
      { q: 'Do I need the original box?', a: 'Often it helps; requirements vary. When unsure, keep packaging through the decision window.' },
      { q: 'What if Amazon auto-approves returns?', a: 'Approval ≠ deadline extension. You still must complete the return process on time.' },
      { q: 'Are holiday rules the only exception?', a: 'No. Electronics, hazmat, personal care, and seller terms create many exceptions. Always check the item.' },
    ],
  },
];

export const PRIMARY_WEIGHTS = {
  fba: 5,
  acos: 4,
  inv: 3,
  unit: 3,
  cpu: 2,
  ret: 3,
};
